#!/bin/sh


# compile the polynomial generator, and generate polynomial test case
cd ../PolynomialGenerator/
g++ PolynomialGenerator.cpp -o generator

# go back to Driver directory and create a temporary directory to hold test cases and outputs
cd ../Driver/

mkdir TempTests
cd TempTests

../../PolynomialGenerator/generator -s 0 -o t_100p -n 100
../../PolynomialGenerator/generator -s 0 -o t_200p -n 200
../../PolynomialGenerator/generator -s 0 -o t_300p -n 300
../../PolynomialGenerator/generator -s 0 -o t_400p -n 400
../../PolynomialGenerator/generator -s 0 -o t_500p -n 500


# go back to the Driver directory and run tests
cd ../


pwd

# 100 polynomial pairs
echo 'Testing on 100 Polynomial Pairs'
./main -h binary -i TempTests/t_100p -o TempTests/o_100p_binary.out -v 1
./main -h funnel-merging -i TempTests/t_100p -o TempTests/o_100p_funnel_merging.out -v 1

echo '\n\n'


# 200 polynomial pairs
echo 'Testing on 200 Polynomial Pairs'
./main -h binary -i TempTests/t_200p -o TempTests/o_200p_binary.out -v 1
./main -h funnel-merging -i TempTests/t_200p -o TempTests/o_200p_funnel_merging.out -v 1

echo '\n\n'


# 300 polynomial pairs
echo 'Testing on 300 Polynomial Pairs'
./main -h binary -i TempTests/t_300p -o TempTests/o_300p_binary.out -v 1
./main -h funnel-merging -i TempTests/t_300p -o TempTests/o_300p_funnel_merging.out -v 1

echo '\n\n'

# 400 polynomial pairs
echo 'Testing on 400 Polynomial Pairs'
./main -h binary -i TempTests/t_400p -o TempTests/o_400p_binary.out -v 1
./main -h funnel-merging -i TempTests/t_400p -o TempTests/o_400p_funnel_merging.out -v 1

echo '\n\n'

# 500 polynomial pairs
echo 'Testing on 500 Polynomial Pairs'
./main -h binary -i TempTests/t_500p -o TempTests/o_500p_binary.out -v 1
./main -h funnel-merging -i TempTests/t_500p -o TempTests/o_500p_funnel_merging.out -v 1

echo '\n\n'


cd TempTests
diff o_100p_binary.out o_100p_funnel_merging.out
diff o_200p_binary.out o_200p_funnel_merging.out
diff o_300p_binary.out o_300p_funnel_merging.out
diff o_400p_binary.out o_400p_funnel_merging.out
diff o_500p_binary.out o_500p_funnel_merging.out



cd ../Driver/

