#!/bin/sh

echo 'PM-OSI-BHC: 100 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_100p_s_0.in

echo 'PM-OSI-BHC: 500 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_500p_s_0.in

echo 'PM-OSI-BHC: 710 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_710p_s_0.in

echo 'PM-OSI-BHC: 1000 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_1000p_s_0.in

echo 'PM-OSI-BHC: 1500 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_1500p_s_0.in

echo 'PM-OSI-BHC: 2100 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_2100p_s_0.in

echo 'PM-OSI-BHC: 2900 pairs - 0 % sparsity'
./main -v 1 -osi -h binary-chaining -i ../Testcases/t_2900p_s_0.in



